// marketing-website/src/pages/analysis.tsx
import { useState } from 'react'
import Head from 'next/head'
import { motion } from 'framer-motion'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { uploadAndAnalyze } from '../api/analysis'

export default function Analysis() {
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [previewUrl, setPreviewUrl] = useState('')
  const [isAnalyzing, setIsAnalyzing] = useState(false)
  const [result, setResult] = useState<any>(null)
  const [selectedModel, setSelectedModel] = useState('qwen3')
  const [error, setError] = useState<string | null>(null)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      setSelectedFile(file)
      const url = URL.createObjectURL(file)
      setPreviewUrl(url)
      setResult(null)
    }
  }

  const handleRemoveFile = () => {
    setSelectedFile(null)
    setPreviewUrl('')
    setResult(null)
  }

  const handleAnalyze = async () => {
    if (!selectedFile) {
      setError('请先选择一张图片')
      return
    }

    setIsAnalyzing(true)
    setError(null)
    
    try {
      const response = await uploadAndAnalyze(selectedFile, selectedModel)
      setResult(response)
    } catch (err) {
      console.error('分析失败:', err)
      setError('分析失败，请重试')
    } finally {
      setIsAnalyzing(false)
    }
  }



  return (
    <>
      <Head>
        <title>植物虫害AI识别 - 在线识别</title>
    <meta name="description" content="使用先进的AI技术识别植物虫害，提供专业的防治建议" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
        <Navbar />
        
        <main className="container mx-auto px-4 py-8 pt-24">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-10"
          >
            <h1 className="text-4xl font-bold text-gray-900 mb-4">植物虫害AI识别</h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              上传植物图片，我们的AI系统将为您快速识别病虫害并提供专业防治建议
            </p>
          </motion.div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* 上传区域 */}
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.1 }}
            >
              <div className="bg-white rounded-xl shadow-lg p-6">
                <h2 className="text-2xl font-semibold text-gray-800 mb-6 flex items-center">
                  <span className="mr-2">📸</span> 上传植物图片
                </h2>
                
                {!previewUrl ? (
                  <div className="border-2 border-dashed border-primary-300 rounded-lg p-8 text-center bg-primary-50">
                    <div className="mb-4">
                      <svg className="mx-auto h-12 w-12 text-primary-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                      </svg>
                    </div>
                    <label htmlFor="file-upload" className="cursor-pointer">
                      <span className="text-primary-600 font-medium">点击上传图片</span>
                      <span className="text-gray-500"> 或拖拽文件到此处</span>
                      <p className="text-sm text-gray-500 mt-2">支持 JPG、PNG、WEBP 格式，大小不超过 10MB</p>
                      <input id="file-upload" name="file-upload" type="file" className="sr-only" accept="image/*" onChange={handleFileChange} />
                    </label>
                  </div>
                ) : (
                  <div className="relative">
                    <img src={previewUrl} alt="预览" className="w-full h-64 object-cover rounded-lg" />
                    <button
                      onClick={handleRemoveFile}
                      className="absolute top-2 right-2 bg-red-500 text-white rounded-full p-2 hover:bg-red-600 transition-colors"
                    >
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clipRule="evenodd" />
                      </svg>
                    </button>
                  </div>
                )}

                <div className="mb-6">
                  <label className="block text-sm font-medium text-gray-700 mb-2">选择AI模型：</label>
                  <select 
                    value={selectedModel}
                    onChange={(e) => setSelectedModel(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-primary-500 focus:border-primary-500"
                  >
                    <option value="qwen3">QWEN3 (通义千问)</option>
                    <option value="gpt4">GPT-4 Vision</option>
                    <option value="claude">Claude 3</option>
                  </select>
                </div>

                {error && (
                  <div className="mb-6 p-4 bg-red-50 border border-red-200 text-red-700 rounded-md">
                    {error}
                  </div>
                )}

                <button
                  onClick={handleAnalyze}
                  disabled={!selectedFile || isAnalyzing}
                  className="w-full mt-6 bg-primary-600 text-white py-3 px-4 rounded-md font-medium hover:bg-primary-700 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors flex items-center justify-center"
                >
                  {isAnalyzing ? (
                    <>
                      <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      分析中...
                    </>
                  ) : (
                    <>
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
                        <path fillRule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clipRule="evenodd" />
                      </svg>
                      开始分析
                    </>
                  )}
                </button>
              </div>
            </motion.div>

            {/* 结果展示区域 */}
            <motion.div
              initial={{ opacity: 0, x: 30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              {result && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5 }}
                  className="space-y-6"
                >
                  {/* 识别概览 */}
                  <div className="bg-white rounded-xl shadow-lg p-6 border-l-4 border-blue-500">
                    <h3 className="text-lg font-semibold text-gray-800 mb-4">识别概览</h3>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-sm text-gray-600">识别类型</p>
                        <p className="font-medium">{result.identificationType === 'pest' ? '害虫识别' : '病害识别'}</p>
                      </div>
                      <div>
                        <p className="text-sm text-gray-600">置信度</p>
                        <div className="flex items-center">
                          <div className="w-full bg-gray-200 rounded-full h-2.5 mr-2">
                            <div 
                              className="bg-blue-600 h-2.5 rounded-full" 
                              style={{ width: `${(result.confidence || 0) * 100}%` }}
                            ></div>
                          </div>
                          <span className="text-sm">{Math.round((result.confidence || 0) * 100)}%</span>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* 植物信息 */}
                  <div className="bg-green-50 p-6 rounded-lg border border-green-200">
                    <h3 className="text-lg font-semibold text-green-800 mb-3">植物信息</h3>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-sm text-gray-600">植物名称</p>
                        <p className="font-medium">{result.plantName || '未识别'}</p>
                      </div>
                      <div>
                        <p className="text-sm text-gray-600">使用模型</p>
                        <p className="font-medium">{result.modelUsed || selectedModel}</p>
                      </div>
                    </div>
                  </div>

                  {/* 虫害风险评估 */}
                  <div className={`p-6 rounded-lg border ${
                    result.wormRiskLevel >= 3 ? 'bg-red-50 border-red-200' : 
                    result.wormRiskLevel >= 2 ? 'bg-yellow-50 border-yellow-200' : 
                    'bg-green-50 border-green-200'
                  }`}>
                    <h3 className="text-lg font-semibold mb-3">虫害风险评估</h3>
                    <div className="flex items-center mb-3">
                      <div className={`w-4 h-4 rounded-full mr-2 ${
                        result.wormRiskLevel >= 3 ? 'bg-red-500' : 
                        result.wormRiskLevel >= 2 ? 'bg-yellow-500' : 
                        'bg-green-500'
                      }`}></div>
                      <span className="font-medium">
                        {result.wormRiskLevel >= 3 ? '高风险' : 
                         result.wormRiskLevel >= 2 ? '中等风险' : 
                         '低风险'}
                      </span>
                      <span className="ml-2 text-gray-600">({result.wormRiskLevel}/5)</span>
                    </div>
                    <div className="mb-3">
                      <p className="text-sm text-gray-600">虫蛀损伤</p>
                      <p className="font-medium">{result.hasWormDamage ? '检测到虫蛀损伤' : '未检测到虫蛀损伤'}</p>
                    </div>
                    <p className="text-sm text-gray-700">
                      {result.wormRiskLevel >= 3 ? '检测到严重虫害，建议立即采取防治措施' : 
                       result.wormRiskLevel >= 2 ? '存在一定虫害风险，建议密切观察并采取预防措施' : 
                       '虫害风险较低，继续保持良好的种植管理'}
                    </p>
                  </div>

                  {/* 害虫识别 */}
                  {result.identificationType === 'pest' && result.pestName && (
                    <div className="bg-orange-50 p-6 rounded-lg border border-orange-200">
                      <h3 className="text-lg font-semibold text-orange-800 mb-3">害虫识别</h3>
                      <div className="mb-3">
                        <p className="text-sm text-gray-600">害虫名称</p>
                        <p className="font-medium text-lg">{result.pestName}</p>
                      </div>
                      <div className="mb-3">
                        <p className="text-sm text-gray-600">置信度</p>
                        <div className="flex items-center">
                          <div className="w-full bg-gray-200 rounded-full h-2.5 mr-2">
                            <div 
                              className="bg-orange-600 h-2.5 rounded-full" 
                              style={{ width: `${(result.confidence || 0) * 100}%` }}
                            ></div>
                          </div>
                          <span className="text-sm">{Math.round((result.confidence || 0) * 100)}%</span>
                        </div>
                      </div>
                    </div>
                  )}

                  {/* 蚜虫检测 */}
                  <div className={`p-6 rounded-lg border ${
                    result.hasAphid ? 'bg-purple-50 border-purple-200' : 'bg-gray-50 border-gray-200'
                  }`}>
                    <h3 className="text-lg font-semibold mb-3">蚜虫检测</h3>
                    <div className="flex items-center mb-3">
                      <div className={`w-4 h-4 rounded-full mr-2 ${
                        result.hasAphid ? 'bg-purple-500' : 'bg-gray-400'
                      }`}></div>
                      <span className="font-medium">
                        {result.hasAphid ? '检测到蚜虫' : '未检测到蚜虫'}
                      </span>
                    </div>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-sm text-gray-600">蚜虫数量</p>
                        <p className="font-medium">{result.aphidCount || '无'}</p>
                      </div>
                      <div>
                        <p className="text-sm text-gray-600">蚜虫种类</p>
                        <p className="font-medium">{result.aphidSpecies || '无'}</p>
                      </div>
                    </div>
                  </div>

                  {/* 详细分析 */}
                  <div className="bg-blue-50 p-6 rounded-lg border border-blue-200">
                    <h3 className="text-lg font-semibold text-blue-800 mb-3">详细分析</h3>
                    <div className="text-gray-700">
                      {result.detailedAnalysis && result.detailedAnalysis.split('\n').map((line: string, index: number) => (
                        <p key={index} className="mb-2">{line}</p>
                      ))}
                    </div>
                  </div>

                  {/* 防治建议 */}
                  <div className="bg-purple-50 p-6 rounded-lg border border-purple-200">
                    <h3 className="text-lg font-semibold text-purple-800 mb-3">防治建议</h3>
                    <div className="text-gray-700">
                      {result.suggestion && result.suggestion.split('\n').map((line: string, index: number) => (
                        <p key={index} className="mb-2">{line}</p>
                      ))}
                    </div>
                  </div>
                </motion.div>
              )}
            </motion.div>
          </div>
        </main>
        
        <Footer />
      </div>
    </>
  )
}

// web/src/views/Analysis.vue
<template>
  <div class="analysis-page">
    <!-- 导航栏 -->
    <header class="header">
      <div class="container">
        <div class="logo">
          <span class="logo-icon">🌱</span>
          <span class="logo-text">植物病虫害AI识别</span>
        </div>
        <nav class="nav">
          <router-link to="/" class="nav-link">首页</router-link>
          <router-link to="/analysis" class="nav-link active">在线识别</router-link>
          <router-link to="/about" class="nav-link">关于我们</router-link>
        </nav>
      </div>
    </header>

    <div class="main-content">
      <div class="container">
        <h1 class="page-title">在线识别</h1>
        
        <div class="content-grid">
          <!-- 左侧：上传区域 -->
          <div class="upload-section">
            <el-card class="upload-card" shadow="hover">
              <template #header>
                <div class="card-header">
                  <span class="card-title">📸 上传植物图片</span>
                </div>
              </template>
              
              <!-- 图片上传 -->
              <div class="upload-area" v-if="!imageUrl">
                <el-upload
                  class="image-uploader"
                  :show-file-list="false"
                  :before-upload="beforeUpload"
                  :on-change="handleFileChange"
                  :auto-upload="false"
                  drag
                >
                  <div class="upload-placeholder">
                    <el-icon class="upload-icon"><Upload /></el-icon>
                    <div class="upload-text">
                      <p class="upload-title">点击或拖拽图片到这里</p>
                      <p class="upload-hint">支持 JPG、PNG、WEBP 格式，大小不超过 10MB</p>
                    </div>
                  </div>
                </el-upload>
              </div>
              
              <!-- 图片预览 -->
              <div class="image-preview" v-else>
                <img :src="imageUrl" alt="预览图" />
                <div class="preview-actions">
                  <el-button type="danger" size="small" @click="removeImage">
                    <el-icon><Delete /></el-icon>
                    <span>重新选择</span>
                  </el-button>
                </div>
              </div>
              
              <!-- 模型选择 -->
              <div class="model-selector">
                <label class="selector-label">选择AI模型：</label>
                <el-select v-model="selectedModel" placeholder="请选择模型" style="width: 100%">
                  <el-option label="QWEN3 (通义千问)" value="qwen3" />
                  <el-option label="GPT-4 Vision" value="gpt4" />
                  <el-option label="Claude 3" value="claude" />
                </el-select>
              </div>
              
              <!-- 分析按钮 -->
              <el-button 
                type="success" 
                size="large" 
                :loading="analyzing"
                :disabled="!imageFile || analyzing"
                @click="analyzeImage"
                class="analyze-btn"
              >
                <el-icon v-if="!analyzing"><Search /></el-icon>
                <span>{{ analyzing ? '分析中...' : '开始分析' }}</span>
              </el-button>
            </el-card>
          </div>
          
          <!-- 右侧：结果展示 -->
          <div class="result-section">
            <el-card class="result-card" shadow="hover" v-if="result">
              <template #header>
                <div class="card-header">
                  <span class="card-title">📊 分析结果</span>
                </div>
              </template>
              
              <!-- 植物信息 -->
              <div class="plant-info" v-if="result.plantName">
                <div class="info-icon">🌿</div>
                <div class="info-content">
                  <span class="info-label">识别植物</span>
                  <span class="info-value">{{ result.plantName }}</span>
                </div>
              </div>
              
              <!-- 虫蛀风险 -->
              <div class="risk-section">
                <h3 class="section-title">
                  <span class="title-icon">🐛</span>
                  虫蛀风险评估
                </h3>
                <div class="risk-level">
                  <el-progress 
                    :percentage="(result.wormRiskLevel || 0) * 25" 
                    :color="getRiskColor(result.wormRiskLevel)"
                    :stroke-width="20"
                  />
                  <span class="risk-text">{{ getRiskText(result.wormRiskLevel) }}</span>
                </div>
              </div>
              
              <!-- 蚜虫检测 -->
              <div class="aphid-section">
                <h3 class="section-title">
                  <span class="title-icon">🦗</span>
                  蚜虫检测
                </h3>
                <el-alert
                  :title="result.hasAphid ? '检测到蚜虫' : '未检测到蚜虫'"
                  :type="result.hasAphid ? 'error' : 'success'"
                  :closable="false"
                  show-icon
                >
                  <template v-if="result.hasAphid">
                    <p>数量估计：{{ result.aphidCount || '未知' }}</p>
                  </template>
                </el-alert>
              </div>
              
              <!-- 详细分析 -->
              <div class="analysis-section" v-if="result.detailedAnalysis">
                <h3 class="section-title">
                  <span class="title-icon">📋</span>
                  详细分析
                </h3>
                <div class="analysis-content">
                  <p>{{ result.detailedAnalysis }}</p>
                </div>
              </div>
              
              <!-- 防治建议 -->
              <div class="suggestion-section" v-if="result.suggestion">
                <h3 class="section-title">
                  <span class="title-icon">💊</span>
                  防治建议
                </h3>
                <div class="suggestion-content">
                  <p>{{ result.suggestion }}</p>
                </div>
              </div>
              
              <!-- 模型信息 -->
              <div class="model-info">
                <el-tag type="info" size="small">
                  分析模型：{{ result.modelUsed || '未知' }}
                </el-tag>
              </div>
            </el-card>
            
            <!-- 空状态 -->
            <el-card class="empty-card" shadow="hover" v-else>
              <el-empty description="上传图片后将在此显示分析结果">
                <template #image>
                  <div class="empty-icon">📊</div>
                </template>
              </el-empty>
            </el-card>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Upload, Delete, Search } from '@element-plus/icons-vue'
import { uploadAndAnalyze } from '@/api/analysis'

const imageFile = ref(null)
const imageUrl = ref('')
const selectedModel = ref('qwen3')
const analyzing = ref(false)
const result = ref(null)

// 文件选择前验证
const beforeUpload = (file) => {
  const isImage = file.type.startsWith('image/')
  const isLt10M = file.size / 1024 / 1024 < 10

  if (!isImage) {
    ElMessage.error('只能上传图片文件!')
    return false
  }
  if (!isLt10M) {
    ElMessage.error('图片大小不能超过 10MB!')
    return false
  }
  return true
}

// 处理文件变化
const handleFileChange = (file) => {
  if (beforeUpload(file.raw)) {
    imageFile.value = file.raw
    imageUrl.value = URL.createObjectURL(file.raw)
  }
}

// 移除图片
const removeImage = () => {
  imageFile.value = null
  imageUrl.value = ''
  result.value = null
}

// 分析图片
const analyzeImage = async () => {
  if (!imageFile.value) {
    ElMessage.warning('请先上传图片')
    return
  }
  
  analyzing.value = true
  
  try {
    const res = await uploadAndAnalyze(imageFile.value, selectedModel.value)
    result.value = res
    
    if (res.success) {
      ElMessage.success('分析完成')
    } else {
      ElMessage.error(res.errorMessage || '分析失败')
    }
  } catch (error) {
    console.error('分析失败', error)
    ElMessage.error(error.message || '分析失败，请稍后重试')
  } finally {
    analyzing.value = false
  }
}

// 获取风险等级文本
const getRiskText = (level) => {
  const texts = ['无风险', '低风险', '中风险', '高风险']
  return texts[level] || '未知'
}

// 获取风险等级颜色
const getRiskColor = (level) => {
  const colors = ['#67C23A', '#E6A23C', '#F56C6C', '#F56C6C']
  return colors[level] || '#909399'
}
</script>

<style scoped>
.analysis-page {
  min-height: 100vh;
  background: linear-gradient(135deg, #E8F5E9 0%, #F1F8E9 100%);
}

/* 复用首页的header样式 */
.header {
  background: rgba(255, 255, 255, 0.95);
  backdrop-filter: blur(10px);
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
  position: sticky;
  top: 0;
  z-index: 1000;
}

.header .container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 70px;
}

.logo {
  display: flex;
  align-items: center;
  gap: 10px;
  font-size: 24px;
  font-weight: bold;
  color: var(--primary-color);
}

.logo-icon {
  font-size: 32px;
}

.nav {
  display: flex;
  gap: 30px;
}

.nav-link {
  text-decoration: none;
  color: var(--text-primary);
  font-size: 16px;
  font-weight: 500;
  padding: 8px 16px;
  border-radius: 8px;
  transition: all 0.3s;
}

.nav-link:hover,
.nav-link.active {
  color: var(--primary-color);
  background: rgba(76, 175, 80, 0.1);
}

/* 主内容 */
.main-content {
  padding: 40px 20px;
}

.container {
  max-width: 1400px;
  margin: 0 auto;
}

.page-title {
  text-align: center;
  font-size: 40px;
  color: var(--text-primary);
  margin-bottom: 40px;
}

.content-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 30px;
}

.upload-card,
.result-card,
.empty-card {
  height: fit-content;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.card-title {
  font-size: 20px;
  font-weight: bold;
}

/* 上传区域 */
.upload-area {
  margin-bottom: 20px;
}

.image-uploader :deep(.el-upload) {
  width: 100%;
}

.image-uploader :deep(.el-upload-dragger) {
  width: 100%;
  height: 300px;
  border: 2px dashed var(--primary-color);
  border-radius: 12px;
  background: #F5F5F5;
}

.upload-placeholder {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
}

.upload-icon {
  font-size: 60px;
  color: var(--primary-color);
  margin-bottom: 20px;
}

.upload-title {
  font-size: 18px;
  color: var(--text-primary);
  margin-bottom: 10px;
}

.upload-hint {
  font-size: 14px;
  color: var(--text-muted);
}

/* 图片预览 */
.image-preview {
  position: relative;
  margin-bottom: 20px;
}

.image-preview img {
  width: 100%;
  max-height: 400px;
  object-fit: contain;
  border-radius: 12px;
}

.preview-actions {
  margin-top: 15px;
  text-align: center;
}

/* 模型选择 */
.model-selector {
  margin-bottom: 20px;
}

.selector-label {
  display: block;
  font-size: 16px;
  font-weight: 500;
  color: var(--text-primary);
  margin-bottom: 10px;
}

/* 分析按钮 */
.analyze-btn {
  width: 100%;
  height: 50px;
  font-size: 18px;
  font-weight: bold;
}

/* 结果展示 */
.plant-info {
  display: flex;
  align-items: center;
  padding: 20px;
  background: linear-gradient(135deg, #E8F5E9 0%, #C8E6C9 100%);
  border-radius: 12px;
  margin-bottom: 20px;
}

.info-icon {
  font-size: 50px;
  margin-right: 20px;
}

.info-content {
  display: flex;
  flex-direction: column;
}

.info-label {
  font-size: 14px;
  color: #66BB6A;
  margin-bottom: 5px;
}

.info-value {
  font-size: 24px;
  font-weight: bold;
  color: #2E7D32;
}

.risk-section,
.aphid-section,
.analysis-section,
.suggestion-section {
  margin-bottom: 25px;
}

.section-title {
  display: flex;
  align-items: center;
  font-size: 18px;
  font-weight: bold;
  color: var(--text-primary);
  margin-bottom: 15px;
}

.title-icon {
  font-size: 24px;
  margin-right: 10px;
}

.risk-level {
  margin-top: 10px;
}

.risk-text {
  display: block;
  margin-top: 10px;
  font-size: 16px;
  color: var(--text-secondary);
  text-align: right;
}

.analysis-content,
.suggestion-content {
  padding: 15px;
  background: #F5F5F5;
  border-radius: 8px;
  line-height: 1.8;
  color: var(--text-secondary);
}

.suggestion-content {
  background: #FFF3E0;
}

.model-info {
  margin-top: 20px;
  text-align: center;
}

.empty-card {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 400px;
}

.empty-icon {
  font-size: 100px;
}

/* 响应式设计 */
@media (max-width: 968px) {
  .content-grid {
    grid-template-columns: 1fr;
  }
}
</style>
